apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-watcher
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-watcher
  template:
    metadata:
      labels:
        app: node-watcher
    spec:
      serviceAccountName: node-watcher
      containers:
      - name: node-watcher
        image: emruzhossain/node-watcher:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-watcher
  namespace: kube-system
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-watcher-permissions
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["pods","persistentvolumeclaims"]
  verbs: ["get", "list","watch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-watcher-permissions
subjects:
- kind: ServiceAccount
  name: node-watcher
  namespace: kube-system
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: node-watcher-permissions
